### ISSUE TITLE
CFHTLens star/gal classifier?

### ISSUE THREAD

**Issue by cdfassnacht** [eduardrusu/zMstarPDF#4]
@drphilmarshall What was that you were saying about using the CFHTLens stars and galaxies to train a machine learning algorithm?

**Comment by drphilmarshall** [comment]
Right! The thought was that since CFHTLenS did a lot of extra work fitting
star and galaxy SEDs to their measured object colors, their star-gal
classifications should be _much_ better than the SExtractor `CLASS_STAR`
values. Our problem is, how to best use _our_ colors, to make the best
star-gal classification we can?

I was suggesting that we take the CFHTLenS u, g, r, i magnitudes, and some
standard size measure, and train a machine learning classifier using their
star and galaxy labels. Once we have something that can classify CFHTLS
objects, we then apply it to our own u, g, r, i magnitudes, and the same
standard size measure, and make better star-gal classifications.

For the machine learning: Random Forest works pretty well, and doesn't seem
to need _that_ much tuning. Here's Josh Bloom's ipython notebook demo of a
simple RF classifier:

http://nbviewer.ipython.org/github/profjsb/ctu2015/blob/master/machine-learning-on-SDSS.ipynb

I'd suggest we start by trying to adapt this notebook to our problem. Could
be a nice hack day project.

**Comment by eduardrusu** [comment]
Thanks for the link Phil! Looks like a powerful technique, I'll try to find the time to learn it. 
I think we should not use it on the lens fields, because we have different filters, resolution, depth, possible systematics on photometry etc. For these fields, I intend to use the same technique that CFHTLens uses (morphology and template fitting) for the same magnitude bins, but making use of all the filters we have. I intend to calibrate this using B1608, for which we have deep HST coverage in r band, and therefore can identify stars more reliably based on morphology. 
However, if we want to extend the classification of CFHTLens objects fainter than i=23, I think machine learning is the way to go. It will be time saving, since we don't need to refit spectral templates to each object.

**Comment by eduardrusu** [comment]
By the way, this is the classification that CFHTLens uses (Coupon 2009): 
- i<21 stars: flux_radius < limiting value 
- 21 < i < 23 stars: flux_radius < limiting value and chi2_star < chi2_gal/2 (the factor of 2 chosen based on tests with spectroscopic sample); gal: flux_radius > limiting value or chi2_star > chi2_gal/2
- i>23: all objects flagged as galaxies

**Comment by eduardrusu** [comment]
Do we want/need to extend the classification to i>23? Since we take ratios of weights, does it matter, as long as we use the same classification for the lens fields? A test for systematics would be to recompute the histograms both with improved classification for i=23-24, and without. W4 is known to have a larger star fraction than the other fields, yet the histograms show that the weights computed for this field are similar to the others, therefore it doesn't seem that accurate star/galaxy classification matters much.
